Ruby on Rails/ruby_blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :all_blogs
  resources :about
 # resources :categories
  resources :blogs
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root  "all_blogs#index"  

end


 

Ruby on Rails/ruby_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Ruby on Rails/ruby_blog/app/models/blog.rb
class Blog < ApplicationRecord
    
    belongs_to :category    
    has_rich_text :content    
    has_one_attached  :image
    belongs_to :user
    
    

    def self.search(search)
        if search 
            blog = Blog.find_by(title: search)
            if blog
                self.where(id: blog)
            else
                Blog.all
            end
        else
        Blog.all
        end
    end

end

Ruby on Rails/ruby_blog/app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs
    
end

Ruby on Rails/ruby_blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
  has_one_attached :avatar
    

  attr_accessor :login

  validates :username, presence: true

  
 

end

Ruby on Rails/ruby_blog/app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index        
    end
    
end

Ruby on Rails/ruby_blog/app/controllers/all_blogs_controller.rb
class AllBlogsController < ApplicationController
  #before_action :authenticate_user!
  def index
    @users = User.all
    
    @categories = Category.all
    cate = params[:cate]
    
    if !cate.nil?
      @blogs = Blog.where(:category_id => cate)
     
    else
      @blogs = Blog.all.with_rich_text_content

    end
    
          
    @blogs = Blog.search(params[:search])
         
  end


  private


  def blog_params
    params.require(:blog).permit(:title, :description, :content, :category_id, :user_id, :search)
    
  end



  
end

Ruby on Rails/ruby_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
    #before_action :authenticate_user!
    
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:username, :name, :email, :password, :password_confirmation, :avatar])
    devise_parameter_sanitizer.permit(:sign_in,
      keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
      keys: [:username, :name, :email, :password_confirmation, :current_password, :avatar])
  end

  #@user.avatar.attach(params[:avatar])
  
end

Ruby on Rails/ruby_blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  def index
    
    @categories = Category.all
    
    cate = params[:cate]
    
    if !cate.nil?
      @blogs = Blog.where(:category_id => cate)
    else

      redirect_to root_path
    end  
      
  end

  def show    
    #@user = User.find(params[:id])
    @blog = Blog.find(params[:id])
    if @blog.nil?
      redirect_to :action => :index
    end    
    
  end

  def new
    @blog = Blog.new
  end

  

  def create
    #@users = User.all
    @blog = current_user.blogs.create!(blog_params)
    if @blog.save
      redirect_to @blog
    else
      render :new
   end
  end

  def edit
    @blog = Blog.find(params[:id])

    if current_user.id == @blog.user_id
    
    else
      redirect_to root_path
    end
  end

 
  def update
    
    @blog = Blog.find(params[:id])
    
    if current_user.id == @blog.user_id
      @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy 
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to :action => :index, status: 303
  
    

  end
  private


  def blog_params
    params.require(:blog).permit(:title, :description, :content, :category_id, :user_id, )
    
  end
end

Ruby on Rails/ruby_blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /categories or /categories.json
  def index
    @categories = Category.all
    
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    
    
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id]) 
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

Ruby on Rails/ruby_blog/app/helpers/about_helper.rb
module AboutHelper
end

Ruby on Rails/ruby_blog/app/helpers/all_blogs_helper.rb
module AllBlogsHelper
end

Ruby on Rails/ruby_blog/app/helpers/application_helper.rb
module ApplicationHelper

  
end

Ruby on Rails/ruby_blog/app/helpers/blogs_helper.rb
module BlogsHelper
end

Ruby on Rails/ruby_blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

Ruby on Rails/ruby_blog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

Ruby on Rails/ruby_blog/app/views/categories/_category.html.erb
  <tr>    
      <th class="col col-lg-11">
        <%=  link_to category.category, blogs_path(:cate => category.id), class: "link btn btn-outline-secondary"%> 
          
      </th>
      

      <% if false %>
      <td>
        <%= link_to "Edit", edit_category_path(category), class: "btn btn-outline-primary btn-sm " %>  
      </td>
      
      
     
      <!-- #Removed the delete button until fix the error while delete a cetegory linked to a blog
      <td>
        <%= button_to "Delete", category, method: :delete, class: "btn btn-danger" %>
      </td>
      -->
      <%end%>
  </tr>
    
 

Ruby on Rails/ruby_blog/app/views/categories/_form.html.erb
                   
    <%= form_for @category do |form| %>
        <div class= "mb-3">                                        
          <%= form.text_field :category, required: true, placeholder: "Create a category here", maxlength: 30, class: "form-control" %>
          
        </div>
       
        <div class="btn-align">                   
        <%= form.submit class: "btn btn-success btn-sm" %> 
        </div>
        <!-- # Inactivating this button for a while
        <div class="btn-align">
        <%=  link_to "View Category", blogs_path(:cate => @category.id), class: "btn btn-primary btn-sm"%>
        </div>
        -->
        <div class="btn-align">
        <%= link_to "Back to Categories", categories_path, class: "btn btn-secondary btn-sm" %>  
        </div>                  
    <% end %>                
              

Ruby on Rails/ruby_blog/app/views/categories/edit.html.erb
<p style="color: green"><%= notice %></p>
<section class="vh-150  py-5 " >
  <div class="container py-5 h-100 " >
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-6">
        <div class="card-category">
          <div class="card-body p-4 ">
            <h1 class="text-center my-3 pb-3"> Edit this Category </h1>
                                   
                <%= render "form", category: @category %> 
                 <div class="btn-align-2">
                    <%=  link_to "View Category", blogs_path(:cate => @category.id), class: "btn btn-primary btn-sm"%>
                </div>         
                       
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

Ruby on Rails/ruby_blog/app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<section class="vh-150  py-5 " >
  <div class="container py-5 h-100 " >
    <div class="row d-flex justify-content-center h-100">
      <div class="col col-lg-9 col-xl-6">
        <div class="card-category">
          <div class="card-body p-4 ">
            <h1 class="text-center my-3 pb-3"> Categories </h1>
              <div class="mb-5">
                <%= link_to "Create Category", new_category_path, class: "btn btn-success btn-sm"%>         
              </div>                   
                <table class=" table mb-1 col col-lg-6">                          
                  <% @categories.each do |category| %>
                    <%= render category %>                            
                  <% end %>                        

                </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

Ruby on Rails/ruby_blog/app/views/categories/new.html.erb
<p style="color: green"><%= notice %></p>
<section class="vh-150  py-5 " >
  <div class="container py-5 h-100  " >
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-6">
        <div class="card-category">
          <div class="card-body p-4 contentBlog">
            <h1 class="text-center my-3 pb-3"> Create a new Category </h1>
                                   
                <%= render "form", category: @category %>          
                       
          </div>
        </div>
      </div>
    </div>
  </div>
</section>